/**
 * DAILY TIPS - 150 helpful tips for dashboard users
 * Rotates daily using day-of-year algorithm
 */

const DAILY_TIPS = [
`Offer something tangible upfront — a quick audit, a resource, or a micro-win they can see in minutes. Saying "I can help" means nothing. Showing how you help closes deals. 📊`,
`When reaching out cold, lead with their pain point ("noticed your last campaign got 6 likes") before mentioning your solution. It proves you actually looked. 🎯`,
`Skip the pitch. Ask one sharp question instead: "Want 10+ qualified leads a week without spending a dollar on ads?" — it opens dialogue, not defense. ❓`,
`Cut the jargon or lose the sale. "Book 5 sales calls this week" beats "optimize your customer acquisition funnel" every time. ✍️`,
`Frame every result as before/after: "My client went from 2 inquiries a month to 15 in 3 weeks — here's the one thing we changed." Transformation sells itself. 🔄`,
`Mirror their exact words from their bio, posts, or website copy. When they hear their own language, walls drop instantly. 🪞`,
`Your first line is life or death. Try: "Hey [name], just noticed something about your offer page that's costing you clients..." They'll read line two. 👀`,
`Drop a mini case study in your outreach: "Changed one headline for a client — went from 8% to 23% click-through in 48 hours. Want to see it?" 📝`,
`Trigger one emotion per message. Don't mix urgency with curiosity or relief with fear. Pick one lane and drive it hard. 😌`,
`Replace "Can we connect?" with micro-commitment asks: "Want me to send you a 90-second breakdown of what I'd fix first?" Easy yeses lead to big yeses. 🔑`,
`Weak words kill momentum. Swap "improve" and "help" for hard outcomes: "double your inquiries," "land your first $5K client," "fill your calendar." 💡`,
`White space = readability. Break up your copy with line breaks. Dense blocks of text get skipped. Make it breathable. ✨`,
`Reinforce your core idea through subtle repetition: "More calls mean more revenue. More revenue means freedom. That's why the calls matter most." 🔁`,
`"No" is better than "maybe." If they're not interested, you just saved a week of follow-ups. Move to someone ready to buy. 🚪`,
`Match your tone everywhere. If you're laid-back on Instagram, don't suddenly go corporate in email. Tone inconsistency screams fake. 🧩`,
`The best outreach feels like free consulting: "I spent 10 minutes on your site — here are 3 things pushing people away before they book." Give value first. 🔍`,
`If your outreach isn't working, don't just follow up more — change your angle, offer, or hook entirely. Same message, louder = still ignored. 🛠️`,
`Use simple comparisons: "Your homepage is like a store with no sign — people peek in, get confused, and leave." Metaphors land harder than explanations. 🏪`,
`Call out their objection before they think it: "You're probably already getting leads — but here's why most of them ghost before buying." Preempting builds credibility. 🛡️`,
`Paint them a micro-vision: "Picture waking up to 3 DM inquiries from people ready to pay, no ads needed." Vision sticks when it's vivid and specific. 🎨`,
`Curiosity without clickbait: "Want to see the exact 6-word subject line that got me a 61% open rate last month?" Specific intrigue beats vague hype. 🧩`,
`Lower the friction in every ask. "Let's hop on a call" feels like work. "Want a 2-minute Loom of what I'd change?" feels like a gift. 🎥`,
`Pair logic with emotion in every pitch: "This brought in 8 new clients in May" (logic) + "so you stop stressing about where next month's income comes from" (emotion). ⚖️`,
`Your best-performing lines are gold. If "Let me send you proof in under 60 seconds" works, use it again. Your own wins beat any template. 🔄`,
`Always tie your value to their outcome: "So you stop wasting time on tire-kickers and start closing people who pay on the spot." Make it about their relief, their win. 🏆`,
`People forget your words but never forget how you made them feel — if your outreach feels pushy, they'll ghost. If it feels helpful, they'll reply. 🤝`,
`Showing up consistently beats going hard once. Daily 20-minute outreach blocks crush random 4-hour weekend binges every time. 📅`,
`Ask one more question before you assume you know the answer. "What's blocking you from booking more clients?" often reveals what they'd never volunteer. 🔍`,
`The simplest message wins. If a prospect needs to re-read your DM to understand it, you've already lost them. Clarity closes deals. ✨`,
`Momentum beats perfection. Sending 5 imperfect outreach messages today is worth more than planning the "perfect" campaign next week. 🏃‍♂️`,
`Respect their time like it's money. A 3-line DM that gets to the point shows you value them. A 12-line essay shows you value yourself more. ⏳`,
`Listening beats talking in discovery calls. Ask what they've tried, then pause. Their answer tells you exactly how to close them. 👂`,
`When in doubt, cut half your message. The strongest offers rarely need paragraphs — just one clear promise and proof it works. ✂️`,
`Say thank you when someone replies, books a call, or even says no. Gratitude keeps doors cracked open that logic can't touch. 🙏`,
`Bring calm energy to sales conversations, not desperation. Prospects can smell neediness through the screen — and it repels them instantly. 🔋`,
`People buy the story, not the spreadsheet. "I helped a burnt-out coach go from $2K to $11K months" beats any feature list you've got. 📖`,
`Overpromising kills trust faster than underdelivering. Say what you'll do, then overdeliver quietly. Results beat hype every single time. 🛡️`,
`What's obvious to you is gold to someone else. That "basic" strategy you use to land clients? Package it. Sell it. It's more valuable than you think. 💡`,
`Before you send anything, ask yourself: "Would I actually read this if I got it?" If the answer's no, rewrite it. 📬`,
`Share credit publicly. When you tag a client's win or shout out a referral partner, people notice — and they want to work with you more. 🌟`,
`Reframe every obstacle as a test. "What if I tried this approach?" beats "This isn't working" every time. Experiments reduce fear and spark movement. 🧪`,
`Following through quietly builds more trust than posting about it loudly. Do what you said you'd do, then let them brag about you. 🌱`,
`Timing can make or break a sale. A great offer sent when they're broke or overwhelmed will flop. Ask about timing before you pitch. ⏰`,
`Genuine intent cuts through everything. If you actually care about solving their problem, they'll feel it — and tactics become optional. 🌍`,
`Every "no" teaches you what "yes" looks like. Track why people say no, then adjust your offer, message, or audience until the nos stop. 🚪`,
`Your work environment shapes your close rate. Distractions during sales calls cost you deals. Protect your focus like it's revenue — because it is. 🪴`,
`Simplify every decision by asking: "Does this get me closer to a booked call or a signed client?" If not, delete it from your day. ➡️`,
`One kind message can turn a cold lead warm. "Hey, no pressure, just checking if you're still interested" works better than you think. 💌`,
`Review your week every Friday. What outreach worked? What flopped? Progress hides in patterns you only see when you pause and look. 🪞`,
`Every interaction either builds trust or chips away at it. Choose your words carefully — especially when you're frustrated or in a rush. 🧩`,
`Confidence comes from reps, not luck. The more sales calls you take, the less you rely on "perfect timing" — because you've seen every objection twice. 🎯`,
`Build a simple morning routine and protect it. Even 15 minutes of focused prep before outreach anchors your entire day and sharpens your messaging. ☕`,
`How you start the conversation sets the tone for everything. Lead with curiosity, not a pitch, and watch how fast defenses drop. 🚀`,
`Boundaries protect your best work. Saying no to $500 distraction clients means saying yes to $5K dream clients. Guard your calendar ruthlessly. 🛑`,
`Measure what you control — messages sent, calls booked, follow-ups done. Stop obsessing over what you can't: their decision, the economy, the algorithm. 📊`,
`Asking for help isn't weakness, it's strategy. "How'd you handle this objection?" saves you months of trial and error. Steal insights shamelessly. 🤲`,
`Simplicity is hard work. Cutting a pitch from 8 sentences to 3 that hit harder? That takes effort. But it's the effort that converts. ✂️`,
`Stay calm when a prospect ghosts or pushes back. Desperation replies kill deals. A composed follow-up two days later often closes them. 🌊`,
`Long-term clients come from short-term honesty. If your service isn't the right fit, say so. They'll remember you when it is — and refer others. 🔑`,
`Attention is currency. Spend yours on high-intent leads, not looky-loos who "might be interested eventually." Your time has a price tag. 👀`,
`Stay curious or get left behind. What worked last year might flop today. Test new platforms, new hooks, new angles — the market won't wait. 🌍`,
`One action repeated daily beats random hustle any week. Send 10 DMs every morning and you'll close more than someone who "grinds" inconsistently. 🔄`,
`Clarity in your offer makes every decision simple. If a task doesn't serve "book more discovery calls," drop it. Ruthless focus wins. 🎯`,
`The best closers are always learning. Read what top performers share, study their messaging, and adapt it to your voice. Leading means staying a student. 📚`,
`Pause before you reply to a difficult prospect. The smartest move in tense conversations is often the one you don't send immediately. ⏸️`,
`Trust builds slow and shatters fast. One missed deadline or half-truth can undo months of goodwill. Handle it like glass, because it is. 🪞`,
`Consistency beats flashy gestures in client relationships too. A quick check-in every two weeks builds more loyalty than one grand surprise. 💌`,
`The most convincing marketing is proof you live it. If you sell lead generation but have no leads yourself, nobody's buying. Practice what you pitch. 👣`,
`Every solution creates new problems. Land 20 clients? Now you need systems. Design for what's next, not just what's now. ⚖️`,
`Change feels risky, but staying stuck is riskier. That platform you're avoiding or offer you're scared to test? The market's already moving without you. ⏳`,
`Quiet execution beats loud promises. Deliver results in silence, let clients do the talking, and watch referrals roll in without you chasing them. 🧘`,
`Anticipation sells harder than the thing itself. Tease a result before revealing the method — "Wait till you see what happened next" keeps them leaning in. 🎁`,
`Respect their buying pace. Not everyone decides in a day. Nurture slow leads without pressure, and they'll close when they're ready — often bigger. ⏱️`,
`Ideas mean nothing without execution. A "perfect funnel" you never build loses to a messy one you launch today. Action filters everything. 🔨`,
`Balance ambition with rest or burn out before you scale. Late nights feel productive until they tank your sales calls. Protect your energy like revenue. 🌙`,
`Patience often closes faster than urgency. Rushing a prospect into a call they're not ready for wastes both your time. Let them come to you warm. 🐢`,
`Stack small wins daily and confidence becomes unshakable. Every booked call, every closed deal, every good reply — they compound into belief that carries you through dry spells. 🧱`,
`Integrity is doing the right thing when nobody's watching. Deliver value even when the client won't notice — it shapes who you become, and that shows up in every pitch. 🌙`,
`Creativity thrives in constraints. Limited budget? No audience? Good. Limits force you to find angles your well-funded competitors never consider. 🎨`,
`You can't control if they buy, but you control the effort you bring. Show up sharp to every call, send every follow-up, refine every message. That's the game. 💪`,
`Respect isn't claimed in your pitch, it's earned through consistent behavior. Do what you say, when you say it, and watch how fast people start saying yes. 🛡️`,
`The calmest voice in the sales call often wins. Desperation raises pitch and speed — confidence lowers both. Speak slow, stay steady, close more. 🌾`,
`Choose long-term reputation over short-term cash. That shady upsell might work once, but word spreads fast. Protect your name like it's your only asset. 📜`,
`Reflection without action is daydreaming; action without reflection is chaos. Every Friday, review what worked. Every Monday, do more of it. 🔄`,
`Empathy is a closing skill. Step into their world — their fears, their budget, their boss's opinion — and your pitch writes itself. 👓`,
`Opportunities don't announce themselves, they show up disguised as boring tasks. That unglamorous follow-up? That's revenue hiding in plain sight. 🔍`,
`Listen fully on discovery calls and they'll tell you exactly how to close them. Most people pitch while the prospect's still talking. Don't. 👂`,
`The harder the truth, the more important it is to say it. "This won't work for you yet" loses a sale today but earns trust that brings three more later. 🗝️`,
`Discipline is choosing what you want most over what you want now. Skipping Netflix to send 15 outreach messages? That's the split-second that changes income. ⏳`,
`Your best ideas come when you're not forcing them. Step away from the screen, walk, shower — let your brain connect dots in silence. 🌌`,
`Respect deadlines you set for yourself. If you say you'll follow up Tuesday, do it Tuesday. Self-trust is the foundation of every other skill. ⏰`,
`Authenticity attracts more than perfection. A real story about a failed launch and what you learned? That builds trust faster than any highlight reel. 🌿`,
`Generosity compounds in business. Give free value, make intros, share insights — it circles back in referrals and opportunities you can't predict. 🔄`,
`Words carry weight in every message. Use them to encourage action, not create doubt. "Here's what's possible" beats "Here's what's wrong" every time. 🪶`,
`When overwhelmed, simplify ruthlessly. What's the one task that moves the needle today? Do that. Ignore everything else until it's done. 🧭`,
`Gratitude is a business multiplier. Thank people for replies, for referrals, for showing up to calls. It turns one transaction into an ongoing relationship. 🙏`,
`Every ending opens space for a beginning. Lost a client? Good. Now you have room for one who pays better and respects your time. 🚪`,
`Your environment whispers into your habits. Notifications during outreach kill your close rate. Design your workspace for focus, not distraction. 🖼️`,
`Confidence isn't knowing everything, it's being willing to say "I don't know, but I'll find out." Prospects trust honesty over fake expertise every time. 🌱`,
`True leadership means creating other leaders. Train your clients so well they don't need you forever — they'll send everyone they know before they leave. 👑`,
`Doubt grows in silence and kills deals. If something feels off about the offer or timeline, ask early. Clarity now prevents ghosting later. 🌫️`,
`Consistency in small habits quietly rewrites your income. Ten DMs every morning for 90 days? That's not discipline, that's a revenue system. 🪴`,
`Anger clouds every sales decision. If a prospect pisses you off, close the laptop and respond tomorrow. Emotional replies lose deals you'd have closed calm. 🌩️`,
`Respect starts with how you treat people who can't pay you yet. That broke follower asking questions? Help them. They'll buy when they're ready — and tell others. 🤲`,
`Time spent preparing never gets wasted. Fifteen minutes researching a prospect before outreach cuts your close time in half. Do the work upfront. 🛠️`,
`Self-awareness is the foundation of better pitches. Know when you ramble, when you sound desperate, when you oversell. Fix your patterns, fix your income. 🪞`,
`Courage is taking the sales call even when imposter syndrome is screaming. Fear doesn't leave — you just get better at moving through it. 🦁`,
`Apologies mean nothing without changed behavior. Missed a deadline? Say sorry once, then never miss again. Action proves sincerity, words don't. 🔑`,
`Adaptability is survival in business. That offer that worked in January might flop by June. Pivot fast or get left behind — the market doesn't wait. 🌊`,
`Humility makes room for growth; pride blocks it. The day you think you've mastered sales is the day your close rate starts dropping. 📚`,
`Focus is the rarest currency in business. Guard it from Slack pings, random DMs, and shiny objects. Protected attention = closed deals. 🎯`,
`Joy in small moments builds resilience for dry months. Celebrate the booked call, the good reply, the micro-win. Momentum starts with noticing progress. 🌸`,
`Fairness isn't treating every lead the same — it's giving each what they need. Some need education, some need urgency, some need space. Read the room. ⚖️`,
`Overcomplication hides revenue. If your pitch needs a flowchart to explain, simplify until the next step is obvious. Confusion kills conversions. 🧭`,
`How you end conversations matters as much as how you start them. "I'll follow up Friday" with no follow-up? You just torched trust forever. 🔚`,
`Rest is productive, burnout erases progress. You can't close deals when you're fried. Protect your energy or lose the month. 🛌`,
`Treat every commitment like a promise. "I'll send that over today" isn't casual — it's your reputation on the line. Reliability builds quiet respect. 📜`,
`Forgiveness frees you from dead weight. That client who ghosted? Let it go. Resentment clogs your pipeline and poisons your next pitch. 🕊️`,
`Your habits are stronger than motivation will ever be. Build a system for outreach and follow-ups — willpower runs out, systems don't. ⚙️`,
`True influence is when prospects adopt your perspective, not just your offer. Shift how they see their problem, and the sale becomes inevitable. 🌟`,
`Great questions close more than great pitches. "What's the real cost of staying stuck here?" cuts deeper than any feature list you've memorized. ❓`,
`If you want respect, model it first in every interaction. Prospects mirror your energy — show up professional, they'll treat you professional. 🪞`,
`Flexibility isn't weakness, it's resilience. That objection you didn't plan for? Adapt in real time. Rigid scripts lose to responsive conversations. 🌾`,
`Celebrate progress, not just closed deals. Booked three calls this week? That's forward motion. Wins along the way fuel the bigger wins ahead. 🎉`,
`Consistency of character gets remembered longer than one brilliant pitch. Be the same person in the DM, on the call, and after the sale. That's brand. 🌙`,
`Kindness in business costs nothing but often returns everything. A patient reply to a confused prospect? They remember that when they're ready to buy. 🌷`,
`Plans create direction, but flexibility keeps you closing when plans fall apart. The script breaks, WiFi drops, they bring objections you've never heard — adapt anyway. 🛤️`,
`Patience with people pays as much as patience with results. Some leads need three months to decide. Nurture without pressure and close them when they're ready. ⏳`,
`The fastest way to learn sales is to teach what you know. Explain your process to someone else and you'll spot holes in your own pitch instantly. 🧑‍🏫`,
`True wealth is time freedom, not just revenue. A $10K month where you're buried in delivery isn't freedom. Build offers that scale without drowning you. 💰➡️🕒`,
`Comparison steals momentum. Stop checking what other coaches are charging or closing. Measure against your own last month — that's the only race that matters. 📏`,
`Integrity shows up in the small stuff when nobody's watching. Honoring a refund request, crediting a referral, being honest about timelines — that's the real test. 🕯️`,
`Clear boundaries are respect for both sides. "I don't work weekends" protects your energy and shows clients you value the time you do give them. 🛑`,
`Optimism isn't ignoring problems, it's believing they're solvable. Lost a deal? Good. Now you know what objection to handle better next time. ☀️`,
`Listening to understand beats listening to reply. On sales calls, pause after they answer. The silence pulls out the real objection they're hiding. 👂`,
`Strong client relationships are built through consistency, not grand gestures. Weekly check-ins beat one surprise gift every six months. 🤝`,
`The quality of your questions shapes the quality of your business. Ask better questions in discovery calls, and you'll close deals others can't. ❓`,
`Taking responsibility gives you power to change what happens next. Blame the algorithm or fix your messaging — only one of those makes you money. 🔑`,
`Simplicity persuades, complexity creates doubt. If they need to "think about it," your offer was probably too complicated. Strip it down. ✨`,
`Confidence grows every time you keep a promise to yourself. Said you'd send ten DMs today? Do it. Self-trust becomes close-rate trust. 📜`,
`Your perspective expands when you study industries outside your own. How do real estate agents close? What do SaaS companies automate? Steal and adapt. 🌍`,
`Rest without guilt is a sign you've leveled up. Taking Sunday off isn't lazy when Monday's pipeline is full. Earned rest hits different. 🌙`,
`A calm mind sees opportunities a frantic one misses. Desperation makes you pitch everyone. Clarity makes you pick the right ones and close them. 🌊`,
`Every "failure" is just data for the next attempt. That offer that flopped? Now you know what messaging doesn't work. Adjust and relaunch. 📊`,
`People forget your wins but remember your character. Close a deal, great. Close it with integrity and they'll refer you for years. 🌟`,
`Habits shape income more than inspiration ever will. Waiting to "feel motivated" to do outreach? You'll stay broke. Build the routine, results follow. 🧱`,
`Adaptation isn't giving up, it's finding another way forward. Cold DMs not working? Try video. Calls not closing? Rewrite your offer. Move or die. 🔄`,
`Trust your future self by making decisions they'll thank you for. Skip the low-ticket client today so you have space for the high-ticket one tomorrow. 🙌`,
`The right environment makes discipline effortless. Work where distractions can't reach you, and suddenly "focus" isn't a battle — it's automatic. 🪴`,
`Gratitude turns scarcity into enough and enough into abundance. Thankful for two clients? That energy attracts three more. Scarcity mindset repels them. 🙏`
];

// Export the tips array
if (typeof window !== 'undefined') {
    window.DAILY_TIPS = DAILY_TIPS;
    console.log('✅ [DailyTips] Tips array loaded with', DAILY_TIPS.length, 'tips');
    
    // Create helper function to get today's tip
    window.getDailyTip = function() {
        const now = new Date();
        const start = new Date(now.getFullYear(), 0, 0);
        const diff = now - start;
        const oneDay = 1000 * 60 * 60 * 24;
        const dayOfYear = Math.floor(diff / oneDay);
        const tipIndex = dayOfYear % DAILY_TIPS.length;
        return DAILY_TIPS[tipIndex];
    };
    
    console.log('✅ [DailyTips] Helper function created');
}
